openapi: "3.0.2"
info:
  title: API for digital library
  version: "1.0"
  description: this is an api speculation about digital library
servers:
  - url: https://library.com
paths:
  /Author:
    get:
      tags:
        - "Author"
      summary: Retrieve all author
      description: A list of account

      responses:
        "200":
          description: A list of author
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"

    post:
      tags:
        - "Author"
      summary: Create a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Author"
      responses:
        "201":
          description: Author created successfully
        "400":
          description: Bad request

    put:
      tags:
        - "Author"
      summary: Update an author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Author"

      responses:
        "200":
          description: Author updated successfully
        "404":
          description: Author not found
        "400":
          description: Bad request

  /Author/{AuthorId}:
    delete:
      tags:
        - "Author"
      summary: Delete a author by id
      responses:
        "204":
          description: Author deleted successfully
        "404":
          description: Author not found

components:
  schemas:
    Author:
      type: object
      properties:
        id_author:
          type: integer
        name:
          type: string
        first_name:
          type: string
        biography:
          type: string
        nationality:
          type: string
        die_date:
          type: string
          format: date
        birth_date:
          type: string
          format: date
